version: '0.2'
ignorePaths:
  - node_modules
  - coverage
  - dist
  - pnpm-lock.yaml
dictionaryDefinitions: []
dictionaries: []
words:
  - alexiosc
  - apollographql
  - aspnetboiler
  - aspnetboilerplate
  - bitjson
  - caddyserver
  - coverallsapp
  - esbuild
  - exonum
  - gitbucket
  - histo
  - logiciel
  - megistos
  - thistogram
ignoreWords: []
import: []
