version: '0.2'
ignorePaths:
  - node_modules
  - coverage
  - dist
  - pnpm-lock.yaml
dictionaryDefinitions: []
dictionaries: []
words:
  - coverallsapp
  - histo
  - thistogram
ignoreWords: []
import: []
