name: ' 🧽 Auto Fix Lint'

on:
  workflow_dispatch:
    inputs:
      base:
        description: The Base Ref to apply the diff
        required: false
        default: 'main'
  push:
    branches: ['main']

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      NEW_BRANCH: lint-${{ inputs.base  || 'main' }}
      REF_BRANCH: ${{ inputs.base || 'main' }}
      PR_TYPE: ci
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ env.REF_BRANCH }}
      - name: Setup
        uses: ./.github/actions/setup
      - name: Lint
        run: |
          pnpm build
          pnpm lint:fix

      - name: PR Body
        id: body
        uses: streetsidesoftware/actions/public/pr-body@v1
        with:
          title: 'Workflow Bot -- Fix Lint'

      - name: PR
        uses: streetsidesoftware/actions/.github/actions/pr@v1
        with:
          commit-message: '${{ env.PR_TYPE }}: ${{ steps.body.outputs.title }}'
          branch: ${{ env.NEW_BRANCH }}
          base: ${{ env.REF_BRANCH }}
          title: '${{ env.PR_TYPE }}: ${{ steps.body.outputs.title }} (${{ env.REF_BRANCH }})'
          body: ${{ steps.body.outputs.body }}
          app_id: ${{ secrets.AUTOMATION_APP_ID }}
          app_private_key: ${{ secrets.AUTOMATION_PRIVATE_KEY }}
