name: ' 🔗 Update Dependencies Main'

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      base:
        description: The Base Ref to apply the diff
        required: false
        default: 'main'

  schedule:
    - cron: '0 12 * * *'

permissions:
  contents: read

jobs:
  update-dependencies:
    if: github.repository_owner == 'streetsidesoftware'
    runs-on: ubuntu-latest
    env:
      NEW_BRANCH: update-dependencies-${{ inputs.base ||  github.ref_name || 'main' }}
      REF_BRANCH: ${{ inputs.base || github.ref_name || 'main' }}
      PR_TYPE: ci
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ env.REF_BRANCH }}

      - name: Setup
        uses: streetsidesoftware/actions/public/setup-node-pnpm@v1

      - name: Install
        run: pnpm install

      - name: Update packages
        run: |
          pnpm up

      - name: Fix Samples
        run: |
          cd samples
          pnpm rm thistogram
          pnpm add ..

      - name: PR Body
        id: body
        uses: streetsidesoftware/actions/public/pr-body@v1
        with:
          title: 'Workflow Bot -- Update ALL Dependencies'
          path: >-
            package.json
            README.md

      - name: PR
        uses: streetsidesoftware/actions/.github/actions/pr@v1
        with:
          commit-message: '${{ env.PR_TYPE }}: ${{ steps.body.outputs.title }}'
          branch: ${{ env.NEW_BRANCH }}
          base: ${{ env.REF_BRANCH }}
          title: '${{ env.PR_TYPE }}: ${{ steps.body.outputs.title }} (${{ env.REF_BRANCH }})'
          body: ${{ steps.body.outputs.body }}
          app_id: ${{ secrets.AUTOMATION_APP_ID }}
          app_private_key: ${{ secrets.AUTOMATION_PRIVATE_KEY }}
